from enum import Enum


class GameStates(Enum):
    PLAYERS_TURN = 1
    ENEMY_TURN = 2
    PLAYER_DEAD = 3
    SHOW_INVENTORY = 4
    SHOW_WEAPON_INVENTORY = 5
    SHOW_ARMOR_INVENTORY = 6
    SHOW_SCROLL_INVENTORY = 7
    SHOW_QUAFF_INVENTORY = 8
    DROP_INVENTORY = 9
    TARGETING = 10
    LEVEL_UP = 11
    CHARACTER_SCREEN = 12
