from enum import Enum


class GameStates(Enum):
    PLAYERS_TURN = 1
    ENEMY_TURN = 2
    PLAYER_DEAD = 3
    SHOW_INVENTORY = 4
    SHOW_WEAPON_INVENTORY = 5
    SHOW_SCROLL_INVENTORY = 6
    DROP_INVENTORY = 7
    TARGETING = 8
    LEVEL_UP = 9
    CHARACTER_SCREEN = 10
